stages:
    - airdrop_test

variables:
    # TEST_UNIT: "test_unit_hh"
    # TEST_INTEGRATION: "test_integration_hh"
    # TEST_PERFORMANCE: "test_performance_hh"
    # TEST_END_TO_END: "test_endtoend_hardhat"
    # DEPLOYER_PRIVATE_KEY: "0xc5e8f61d1ab959b397eecc0a37a6517b8e67a0e7cf1f4bce5591f3ed80199122"
    # GENESIS_GOVERNANCE_PRIVATE_KEY: "0x50777f5a3ce16445e63411bf1e865a2a11d5ca3c4cbc1de00808a52180bd8d3c"
    # GOVERNANCE_PRIVATE_KEY: "0xd49743deccbccc5dc7baa8e69e5be03298da8688a15dd202e20f15d5e0e9a9fb"
    # TEST_LINTER: "lint"
    # TEST_STATE_CONNECTOR_FILES: "compare_state_connector_file_to_flare_repo"
    YARN_CACHE_DIR: "$CI_PROJECT_DIR/.yarn-cache"

# .yarn-setup: &yarn-setup
#     image: node:latest
#     before_script:
#         - cd airdrop/
#         - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR
        
### Jobs
test-airdrop:
    stage: airdrop_test
    # <<: *yarn-setup
    script:
        - cd airdrop 
        - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR
        - yarn test
