stages:
    # - airdrop_test
    - build_flare

variables:
    YARN_CACHE_DIR: "$CI_PROJECT_DIR/.yarn-cache"

### Jobs
# test-airdrop:
#     stage: airdrop_test
#     image: node:latest
#     script:
#         - cd airdrop 
#         - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR
#         - yarn test

build-flare-network:
    stage: build_flare
    image: golang:1.15
    script:
        - export GOPATH=$HOME/go
        - chmod +x compile.sh
        - bash ./compile.sh
        - chmod +x cmd/single.sh
        - bash ./cmd/single.sh